### ISSUE TITLE
[DOC-64] Update all diagrams / images

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/docs#104]
All Excalidraw diagrams need to be cleaner with a more professional design. Could use either Mermaid (diagrams) or [Figma](https://www.figma.com/files/project/87553454/Team-project?fuid=1131402257984802925) (prettier visuals).

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-64](https://linear.app/tableland/issue/DOC-64/update-all-diagrams-images)</sub>

**Comment by sanderpick** [comment]
We can use Dispatch for any design needs… at some point, if you made a list w/ descriptions of the diagrams we could get them working on it.

**Comment by sanderpick** [comment]
cool, submitted to dispatch.
