### ISSUE TITLE
Spec: update the SQL spec with thew new prepared statements feature

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/docs#14]

**Comment by jsign** [comment]
@carsonfarmer, we're a bit behind here but it's fine.

I bumped the original main project one extra milestone so the main target date is ~Feb 6 now instead of 2 weeks before.
That feels far away, but depending on what we define in the spec this can involve, apart from SDK and validator changes, potential contract changes which might be more sensitive... so I feel the execution pipeline after having the spec feels long and will need time.

I'm planning to write a doc next week to at least get the ball moving for others in the team to jump in.

**Comment by carsonfarmer** [comment]
Yeh awesome, seems like the right call. Did you also update the project in Notion?

**Comment by jsign** [comment]
> Yeh awesome, seems like the right call. Did you also update the project in Notion?

Yes.

**Comment by sanderpick** [comment]
can close for now. we can re-create doc/spec issues when the work becomes planned.
