### ISSUE TITLE
Spec: we need to solve non-determinism for rowids

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/docs#19]
Today we have a problem with letting users manipulate the `rowid` value of a row, which can result in non-determinism because (quoting SQLite spec):
> If the largest ROWID is equal to the largest possible integer (9223372036854775807) then the database engine starts picking positive candidate ROWIDs at random until it finds one that is not previously used.

We've been chatting with @brunocalza about this problem, and it's quite nuanced.

Some notes about this problem:
- If the user defines a `INTEGER PRIMARY KEY` (with or without `AUTOINCREMENT`), it becomes an alias for `rowid`, which is the crux of the problem.
- If we allow the user to assign `9223372036854775807` to `rowid`, `_rowid_`, `oid` then the next insert would be non-deterministic.
- The above bullet also applies to a column name the user-defined as `INTEGER PRIMARY KEY` (with or without `AUTOINCREMENT`).
- `PRIMARY KEY`s that aren't `INTEGER` won't create an alias, which can help narrow down the spec change.

Tentative/fuzzy idea skeleton:
- If a user wants to define an `INTEGER PRIMARY KEY` (with or without `AUTOINCREMENT`), it should have a fixed name defined by the spec (e.g: say `__id`). The idea is to allow the parser to detect invalid queries (see point below)
- The spec should only allow a direct assignment or updates to column names `rowid`, `_rowid_`, `oid` or `__id` with constant values lower than some number X (where `X << 9223372036854775807`).
- User defined `PRIMARY KEY`s which aren't `INTEGER` looks like they are safe to have arbitrary assignments.

The above are some quick notes, we need to jump into a convo about this to dive deeper.
We have to remember to discuss what this means for existing history.

**Comment by brunocalza** [comment]
Here's an example that illustrates the problem:

```
sqlite> create table a (id INTEGER PRIMARY KEY, a TEXT);
sqlite> insert into a  VALUES (9223372036854775807, 'Hello');
sqlite> select rowid, id, a from a;
9223372036854775807|9223372036854775807|Hello
sqlite> insert into a (a)  VALUES ('Hello 2');
sqlite> select rowid, id, a from a;
3587427864672888140|3587427864672888140|Hello 2
9223372036854775807|9223372036854775807|Hello
``` 

If you run that again in a new database, you'll get a different values of `id` and `rowid` for `Hello 2` row.

**Comment by carsonfarmer** [comment]
After a core team discussion, we are proposing the following changes:

- Block all assignment to `rowid` and all aliases (e.g.,  `__rowid__`, `oid`, etc) in the parser
- Force all `PRIMARY KEY INTEGER` directives to implement `PRIMARY KEY INTEGER [AUTOINCREMENT](https://www.sqlite.org/autoinc.html)`, but **do not** directly support the `AUTOINCREMENT` keyword
- Allow `INT` and `TEXT` (and other) `PRIMARY KEY` values to operate without restriction
- Update the spec docs to include the above changes
- Test the above _implicit autoincrement behavior_ to ensure it doesn't break any existing tables
- Document that assignment to an auto incrementing primary key _could_ result in locking a table from further inserts if the max value of the primary key reaches the largest possible integer (9223372036854775807) we support

**Comment by carsonfarmer** [comment]
cc @sanderpick @jsign @brunocalza @dtbuchholz @asutula @joewagner @awmuncy

**Comment by carsonfarmer** [comment]
Note that thanks to initial sleuthing by @jsign, we know that there are **no detected statements** that habe references to:

- `rowid`
- `oid`
- `_rowid_`

And that there are a total of [669 statements](https://pastebin.com/eMVRb7pt) that reference an `INTEGER PRIMARY KEY` (almost entirely `CREATE TABLE` statements), and these correspond to approximately [560 tables](https://pastebin.com/4UZedkWf). Depending on how these tables _use_ the PRIMARY KEY, the above proposed changes may have zero impact on the state of the Tableland network. That is best case scenario, and we'll have to test things out to be sure.

**Comment by brunocalza** [comment]
Just found [this](https://www.sqlite.org/lang_createtable.html#rowids_and_the_integer_primary_key): 
> With one exception noted below, if a rowid table has a primary key that consists of a single column and the declared type of that column is "INTEGER" in any mixture of upper and lower case, then the column becomes an alias for the rowid. Such a column is usually referred to as an "integer primary key". A PRIMARY KEY column only becomes an integer primary key if the declared type name is exactly "INTEGER". Other integer type names like "INT" or "BIGINT" or "SHORT INTEGER" or "UNSIGNED INTEGER" causes the primary key column to behave as an ordinary table column with integer affinity and a unique index, not as an alias for the rowid.
> 
> The exception mentioned above is that if the declaration of a column with declared type "INTEGER" includes an "PRIMARY KEY DESC" clause, it does not become an alias for the rowid and is not classified as an integer primary key. This quirk is not by design. It is due to a bug in early versions of SQLite. But fixing the bug could result in backwards incompatibilities.

In short: `INTEGER PRIMARY KEY DESC` does not become an alias. 

So, for completeness,  we only force `AUTOINCREMENT` on `INTEGER PRIMARY KEY` and `INTEGER PRIMARY KEY ASC`.

**Comment by jsign** [comment]
> There's also a slightly harder case to consider:
> 
> `CREATE TABLE t(x INTEGER, y, z, PRIMARY KEY(x DESC));`
> 
> In that case, the primary is defined at the end as a table constraint and not as a column constraint. I think the solution to that is to transform that statement to
> 
> `CREATE TABLE t(x INTEGER PRIMARY KEY AUTOINCREMENT, y, z );`
> 
> behind the scenes. Because I can't add an `AUTOINCREMENT` to the table constraint. It would be syntactically incorrect.
> 
> cc @jsign @carsonfarmer
> 
> or we block that kind of table constraint. maybe cleaner?

Maybe you meant ` ... PRIMARY KEY(x)` or `... PRIMARY KEY(x ASC)`?

Transforming `... PRIMARY KEY(x DESC)` to `x INTEGER PRIMARY KEY AUTOINCREMENT)` seems to be changing the `DESC` to `ASC`?

**Comment by brunocalza** [comment]
> Maybe you meant ... PRIMARY KEY(x) or ... PRIMARY KEY(x ASC)?

Yeah. I meant `CREATE TABLE t(x INTEGER PRIMARY KEY DESC AUTOINCREMENT, y, z );`

**Comment by jsign** [comment]
> > Maybe you meant ... PRIMARY KEY(x) or ... PRIMARY KEY(x ASC)?
> 
> Yeah. I meant `CREATE TABLE t(x INTEGER PRIMARY KEY DESC AUTOINCREMENT, y, z );`

But in the `DESC` case we don't need to force `AUTOINCREMENT`, right? (your previous comment).

**Comment by brunocalza** [comment]
> But in the DESC case we don't need to force AUTOINCREMENT, right? (your previous comment).

In that case, we need actually. From [docs](https://www.sqlite.org/lang_createtable.html#rowids_and_the_integer_primary_key):

> This means that the following three table declarations all cause the column "x" to be an alias for the rowid (an integer primary key):
>
> CREATE TABLE t(x INTEGER PRIMARY KEY ASC, y, z);
CREATE TABLE t(x INTEGER, y, z, PRIMARY KEY(x ASC));
CREATE TABLE t(x INTEGER, y, z, PRIMARY KEY(x DESC));
>
> But the following declaration does not result in "x" being an alias for the rowid:
>
> CREATE TABLE t(x INTEGER PRIMARY KEY DESC, y, z);

**Comment by jsign** [comment]
> CREATE TABLE t(x INTEGER, y, z, PRIMARY KEY(x DESC));

Wow, OK that's incredibly weird:
- `CREATE TABLE t(x INTEGER, y, z, PRIMARY KEY(x DESC));` is an alias.
- `CREATE TABLE t(x INTEGER PRIMARY KEY DESC, y, z);` isn't an alias.
- In the ASC case, in both styles is an alias.

Cool, now makes sense!

**Comment by carsonfarmer** [comment]
Cripes, ok that is super weird. Right, so the proposed solution here is that we transform the table constraint version to a more canonical direct constraint on the primary key, or we simply block primary key table constraints in the first place, and require that they are specified "inline" so to speak?

**Comment by carsonfarmer** [comment]
I think we can't really block the table constraint version, because IIRC this is the only way to specify a multi-column primary key? Right? So actually, this might be an issue in general!?

**Comment by brunocalza** [comment]
Those are the two options: transforming the table constraint version to a more canonical direct constraint on the primary key or blocking a table constraint primary key that references a single column `INTEGER`. Both should be similar to implement. Not sure which one is best for users.

**Comment by sanderpick** [comment]
The first option (transform constraints) sounds a bit more pleasant for users. With the second option (blocking table constraint), we'd need to return an error that might be hard to understand: "error: table primary key constraints that ref a single column of type `INTEGER` are not supported", or similar. With the first option, it "just works".
