### ISSUE TITLE
Spec: Layout ACL usage patterns to help drive decision on how to apply access rules (yaml vs. SQL)

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/docs#21]

**Comment by carsonfarmer** [comment]
@andrewxhill and I recently discussed this topic, and we have a few thoughts on usage patterns that might prove quite nice to consider. Once this work kicks off, can you please be sure to include myself (@carsonfarmer) and/or @andrewxhill?

**Comment by dtbuchholz** [comment]
@brunocalza @carsonfarmer @avichalp do you know if this is something still needed in the spec or can be closed out?

**Comment by sanderpick** [comment]
closable
