### ISSUE TITLE
Spec: create a living document that describes protocol versions

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/docs#23]

**Comment by carsonfarmer** [comment]
Does this count now? https://github.com/tablelandnetwork/docs/blob/main/specs/validator/tableland-openapi-spec.yaml

**Comment by jsign** [comment]
That document is about the validator API. I don't know if the versioning of the API will be related to the protocol versioning. For example, if we add a new feature to the protocol that doesn't change any API, it doesn't look like that YAML file would reflect that.

**Comment by carsonfarmer** [comment]
Yeh ok, that seems like a good separation. Ok, leaving "as is".
