### ISSUE TITLE
Create documentation for using local-tableland as part of a testing suite

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/docs#25]

**Comment by dtbuchholz** [comment]
@joewagner is there a difference between this issue and https://github.com/tablelandnetwork/docs/issues/26?

**Comment by joewagner** [comment]
@dtbuchholz Good call.  I changed the name of this issue so it captures using l.t. as part of a test suite, and #26 captures usage during app development. 
Does that make sense?  Or would it be better to combine all that into 1?

**Comment by dtbuchholz** [comment]
Ahh I see, yeah I think keeping em separate is fine.

**Comment by dtbuchholz** [comment]
@joewagner double checking on timing for the docs, to make sure i'm not misinterpreting anything. should i move forward and create docs for `local-tableland` now? or, wait until some of the changes you're implementing ([noted in Discord](https://discord.com/channels/592843512312102924/902337528902860820/1036657355192025210)) are merged in the coming weeks?

**Comment by joewagner** [comment]
@dtbuchholz If you have what you need to get going, moving forward with the docs now makes sense to me.
re: the discussion on discord.
The usage tansan.eth is looking for will depend on https://github.com/tablelandnetwork/local-tableland/pull/79 getting finished.

**Comment by dtbuchholz** [comment]
https://docs.tableland.xyz/local-development-testing
