### ISSUE TITLE
Spec: We need to decide on and document a canonical string encoding for our AST / parsed SQL statements

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/docs#28]
It seems like so far we are assuming lowercase string output for all AST components, which seems fine. Since we aren't exposing the AST to the outside world (yet), a canonical encoding (JSON?) of the tree state itself _isn't_ really required at this time... but it would be nice to spec and document the _string encoding_ and finalize that sooner rather than later.

I would propose we stick with lowercase string outputs. It _would_ be nice to have a canonical JSON representation as well, at least to help with future-proofing ourselves to a degree. In that case, I would propose we use lower-case, snake-case field names for all AST nodes and elements.

If we are happy with this, then we can update our spec with this information.

cc @sanderpick @brunocalza @jsign

**Comment by brunocalza** [comment]
You raised a good point. It would be good to formalize how the AST is being encoded as a `string`. 

One thing I'd like to raise visibility is that there are some nuances and corner cases that I had to deal with to produce the encoded `string`. Just to give an example: The statement `update t set (a, b) = (1, 2);` is encoded as `update t set a = 1, b = 2`. And the reason for that is that they are equivalent and I decided to not capture that difference in structure in the AST. So, when producing the `string`, I opted for the most conventional form. Can't remember if there are much more cases like these. This is the biggest, at least, that I can remember.

Also, there's another clarification to make (for completeness), although I think this is not the way we really wanna go. A strict formal spec of the encoding would be hard. We'd have to account for a lot of details such as the number of spaces between tokens and symbols, and how parenthesis and commas are placed, ... 

What we have now was guided by my gut trying to produce a `string` that makes sense. The good thing is that we have tests for a lot of queries. The tests not only check if the parser is producing the right AST but also if the AST is being encoded correctly (by correct I mean what my gut said at the moment haha). An [example](https://github.com/tablelandnetwork/go-sqlparser/blob/main/parser_test.go#L996-L997).

Having said all that, we could have at least provided the docs with some general rules of how the AST is encoded as a string. Some examples:
- it's all lowercase
- the execution is equivalent to the original
- it tries to be as close as possible to the original statement

And for corner cases as the `update` example above, we could simply say how that would be encoded.

**Comment by carsonfarmer** [comment]
Yup, I think this is exactly right, and exactly what we need. The level you suggest (general patterns with some specific cases sprinkled in) is probably the right level of detail, otherwise we might end up blocking ourselves in with too much specificity. The main thing I want to get to is that, when folks use our parser to normalize their results a) there isn't any surprises when they encode as string, and b) they can be certain that hashing two _equivalent_ statements could hash to the same value. So in your nice example above, whether they do something like let `A` = `update t set (a, b) = (1, 2);` or let `B` = `update t set a = 1, b = 2;`, we can be sure that `hash(A) == hash(B)`.
