### ISSUE TITLE
Docs: update to the new APIs

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/docs#8]

**Comment by jsign** [comment]
@dtbuchholz, I'll ping you back here when I got https://github.com/tablelandnetwork/go-tableland/issues/361 done soon-ish. Maybe "updating the docs" will be mostly feeding from that generated output and "copy-pasting" or wiring it.

**Comment by dtbuchholz** [comment]
@jsign sounds good -- pinging me once things are ready for docs works perfectly for me!

**Comment by carsonfarmer** [comment]
That tool that is used there can be used to generate other output types and and be configured quite a bit. Note also that it targets the Slate and similar docs system, which is another docs framework we might want to explore @dtbuchholz?

**Comment by dtbuchholz** [comment]
Hm interesting...yeah, I'll look into Slate as well. Looks pretty simple to use. 

Since I could import a Slate package into some project, I suppose I could still use it within some other framework like markdoc, if needed? Will dig in tho.
