### ISSUE TITLE
[DOC-29] Update query estimator component

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/docs#92]
The docs provide some high-level cost comparisons as static values, via [here](https://docs.google.com/spreadsheets/d/1xfAo-HtUdZmdsPL7Trf8rt3kcit7KfNG-BAepJjkxto/edit#gid=0). It'd be nice to have a query price estimator that does [something like this](https://gist.github.com/dtbuchholz/15fcb612f4bf1b9ff24302d050a5e3ee) under the hood but with a real-time price API or user inputs.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-29](https://linear.app/tableland/issue/DOC-29/update-query-estimator-component)</sub>

**Comment by dtbuchholz** [comment]
A rudimentary, static version is implemented here but is not interactive: [https://github.com/tablelandnetwork/docs/blob/main/src/components/CostEstimator/index.tsx](https://github.com/tablelandnetwork/docs/blob/main/src/components/CostEstimator/index.tsx)

**Comment by sanderpick** [comment]
sg. by dynamic do you mean something like what @awmuncy did with the gas-tracker that reads recent tnxs and get some average?

for the static route, i used the same table create and write statements across diff chains and simply read the value. i'll have to dig to find what those were if you want to do that

**Comment by sanderpick** [comment]
ping

**Comment by sanderpick** [comment]
pong

**Comment by sanderpick** [comment]
pong

**Comment by awmuncy** [comment]
This looks fun.

**Comment by awmuncy** [comment]
Hey look, my comment showed up in Github.

**Comment by dtbuchholz** [comment]
> Hey look, my comment showed up in Github.
Boooo!!
